version: '3.8'
services:
  app:
    image: 'bitrenderfrontenddev'
    container_name: bitrender-frontend-DEV
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - bitrender-frontend-DEV-fish:/home/node/.local/share/fish
    init: true
    command: sleep infinity
    user: node
    ports:
      - '4173'
volumes:
  bitrender-frontend-DEV-fish:
