version: '3.8'
services:
  app:
    container_name: frontend-DEV
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - frontend-DEV-fish:/home/node/.local/share/fish
    init: true
    command: sleep infinity
    user: node
    ports:
      - '1234:1234'

volumes:
  frontend-DEV-fish:
