// Generated by kea-typegen on Sun, 31 Jul 2022 16:47:31 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface logicType extends Logic {
  actionCreators: {
    openApp: () => {
      type: 'open app (logic.core.route.index)';
      payload: {
        value: true;
      };
    };
    openRegisterPage: () => {
      type: 'open register page (logic.core.route.index)';
      payload: {
        value: true;
      };
    };
    openLoginPage: () => {
      type: 'open login page (logic.core.route.index)';
      payload: {
        value: true;
      };
    };
    openUsersPage: () => {
      type: 'open users page (logic.core.route.index)';
      payload: {
        value: true;
      };
    };
    openRolesPage: () => {
      type: 'open roles page (logic.core.route.index)';
      payload: {
        value: true;
      };
    };
    openErrorPage: () => {
      type: 'open error page (logic.core.route.index)';
      payload: {
        value: true;
      };
    };
    replaceWithPrevious: () => {
      type: 'replace with previous (logic.core.route.index)';
      payload: {
        value: true;
      };
    };
  };
  actionKeys: {
    'open app (logic.core.route.index)': 'openApp';
    'open register page (logic.core.route.index)': 'openRegisterPage';
    'open login page (logic.core.route.index)': 'openLoginPage';
    'open users page (logic.core.route.index)': 'openUsersPage';
    'open roles page (logic.core.route.index)': 'openRolesPage';
    'open error page (logic.core.route.index)': 'openErrorPage';
    'replace with previous (logic.core.route.index)': 'replaceWithPrevious';
  };
  actionTypes: {
    openApp: 'open app (logic.core.route.index)';
    openRegisterPage: 'open register page (logic.core.route.index)';
    openLoginPage: 'open login page (logic.core.route.index)';
    openUsersPage: 'open users page (logic.core.route.index)';
    openRolesPage: 'open roles page (logic.core.route.index)';
    openErrorPage: 'open error page (logic.core.route.index)';
    replaceWithPrevious: 'replace with previous (logic.core.route.index)';
  };
  actions: {
    openApp: () => void;
    openRegisterPage: () => void;
    openLoginPage: () => void;
    openUsersPage: () => void;
    openRolesPage: () => void;
    openErrorPage: () => void;
    replaceWithPrevious: () => void;
  };
  defaults: {};
  events: {};
  key: undefined;
  listeners: {};
  path: ['logic', 'core', 'route', 'index'];
  pathString: 'logic.core.route.index';
  props: Record<string, unknown>;
  reducer: (state: any, action: any, fullState: any) => {};
  reducers: {};
  selector: (state: any) => {};
  selectors: {};
  sharedListeners: {};
  values: {};
  _isKea: true;
  _isKeaWithKey: false;
}
