// Generated by kea-typegen on Mon, 15 Aug 2022 17:49:24 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic, BreakPointFunction } from 'kea'

import type { NavigateFunction } from '../../../../node_modules/react-router-dom/index.d'
import type { IRouteValidators } from '../../../validators/interfaces/index'

export interface logicType extends Logic {
  actionCreators: {
    openApp: () => {
      type: 'open app (route)';
      payload: {
        url: string;
      };
    };
    openRegisterPage: () => {
      type: 'open register page (route)';
      payload: {
        url: string;
      };
    };
    openLoginPage: () => {
      type: 'open login page (route)';
      payload: {
        url: string;
      };
    };
    openVerifyPage: (email: string) => {
      type: 'open verify page (route)';
      payload: {
        url: string;
        state: {
          verifyEmail: string;
        };
      };
    };
    openUsersPage: () => {
      type: 'open users page (route)';
      payload: {
        url: string;
      };
    };
    openRolesPage: () => {
      type: 'open roles page (route)';
      payload: {
        url: string;
      };
    };
    openErrorPage: () => {
      type: 'open error page (route)';
      payload: {
        url: string;
      };
    };
    returnToBeforeLogin: () => {
      type: 'return to before login (route)';
      payload: {
        value: true;
      };
    };
  };
  actionKeys: {
    'open app (route)': 'openApp';
    'open register page (route)': 'openRegisterPage';
    'open login page (route)': 'openLoginPage';
    'open verify page (route)': 'openVerifyPage';
    'open users page (route)': 'openUsersPage';
    'open roles page (route)': 'openRolesPage';
    'open error page (route)': 'openErrorPage';
    'return to before login (route)': 'returnToBeforeLogin';
  };
  actionTypes: {
    openApp: 'open app (route)';
    openRegisterPage: 'open register page (route)';
    openLoginPage: 'open login page (route)';
    openVerifyPage: 'open verify page (route)';
    openUsersPage: 'open users page (route)';
    openRolesPage: 'open roles page (route)';
    openErrorPage: 'open error page (route)';
    returnToBeforeLogin: 'return to before login (route)';
  };
  actions: {
    openApp: () => void;
    openRegisterPage: () => void;
    openLoginPage: () => void;
    openVerifyPage: (email: string) => void;
    openUsersPage: () => void;
    openRolesPage: () => void;
    openErrorPage: () => void;
    returnToBeforeLogin: () => void;
  };
  defaults: {};
  events: {};
  key: undefined;
  listeners: {
    openApp: ((
      action: {
        type: 'open app (route)';
        payload: {
          url: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    openRegisterPage: ((
      action: {
        type: 'open register page (route)';
        payload: {
          url: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    openLoginPage: ((
      action: {
        type: 'open login page (route)';
        payload: {
          url: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    openVerifyPage: ((
      action: {
        type: 'open verify page (route)';
        payload: {
          url: string;
          state: {
            verifyEmail: string;
          };
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    openUsersPage: ((
      action: {
        type: 'open users page (route)';
        payload: {
          url: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    openRolesPage: ((
      action: {
        type: 'open roles page (route)';
        payload: {
          url: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    openErrorPage: ((
      action: {
        type: 'open error page (route)';
        payload: {
          url: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    returnToBeforeLogin: ((
      action: {
        type: 'return to before login (route)';
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
  };
  path: ['route'];
  pathString: 'route';
  props: {
    navigate: NavigateFunction;
    deps: {
      routeValidators: IRouteValidators;
    };
  };
  reducer: (state: any, action: any, fullState: any) => {};
  reducers: {};
  selector: (state: any) => {};
  selectors: {};
  sharedListeners: {
    pushRoute: (
      payload: {
        url: string;
        state?: object | undefined;
      },
      breakpoint: BreakPointFunction,
      action: {
        type: string;
        payload: {
          url: string;
          state?: object | undefined;
        };
      },
      previousState: any,
    ) => void | Promise<void>;
    replaceWithPrevious: (
      payload: any,
      breakpoint: BreakPointFunction,
      action: {
        type: string;
        payload: any;
      },
      previousState: any,
    ) => void | Promise<void>;
  };
  values: {};
  _isKea: true;
  _isKeaWithKey: false;
}
