// Generated by kea-typegen on Sun, 10 Jul 2022 10:23:58 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

export interface logicType extends Logic {
  actionCreators: {};
  actionKeys: {};
  actionTypes: {};
  actions: {};
  defaults: {};
  events: {};
  key: undefined;
  listeners: {};
  path: ['logic', 'core', 'app', 'index'];
  pathString: 'logic.core.app.index';
  props: Record<string, unknown>;
  reducer: (state: any, action: any, fullState: any) => {};
  reducers: {};
  selector: (state: any) => {};
  selectors: {};
  sharedListeners: {};
  values: {};
  _isKea: true;
  _isKeaWithKey: false;
}
