// Generated by kea-typegen on Sun, 04 Sep 2022 12:30:04 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface logicType extends Logic {
  actionCreators: {
    setCurrentPage: (currentPage: number) => {
      type: 'set current page (roles.table)';
      payload: {
        currentPage: number;
      };
    };
    setRowsPerPage: (rowsPerPage: number) => {
      type: 'set rows per page (roles.table)';
      payload: {
        rowsPerPage: number;
      };
    };
  };
  actionKeys: {
    'set current page (roles.table)': 'setCurrentPage';
    'set rows per page (roles.table)': 'setRowsPerPage';
  };
  actionTypes: {
    setCurrentPage: 'set current page (roles.table)';
    setRowsPerPage: 'set rows per page (roles.table)';
  };
  actions: {
    setCurrentPage: (currentPage: number) => void;
    setRowsPerPage: (rowsPerPage: number) => void;
  };
  defaults: {
    currentPage: number;
    rowsPerPage: number;
    amountOfRecords: number | null;
  };
  events: {};
  key: undefined;
  listeners: {};
  path: ['roles', 'table'];
  pathString: 'roles.table';
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    currentPage: number;
    rowsPerPage: number;
    amountOfRecords: number | null;
  };
  reducers: {
    currentPage: (state: number, action: any, fullState: any) => number;
    rowsPerPage: (state: number, action: any, fullState: any) => number;
    amountOfRecords: (
      state: number | null,
      action: any,
      fullState: any,
    ) => number | null;
  };
  selector: (state: any) => {
    currentPage: number;
    rowsPerPage: number;
    amountOfRecords: number | null;
  };
  selectors: {
    currentPage: (state: any, props?: any) => number;
    rowsPerPage: (state: any, props?: any) => number;
    amountOfRecords: (state: any, props?: any) => number | null;
  };
  sharedListeners: {};
  values: {
    currentPage: number;
    rowsPerPage: number;
    amountOfRecords: number | null;
  };
  _isKea: true;
  _isKeaWithKey: false;
}
