version: '3.8'

services:
  app:
    image: 'bitrenderbackenddev'
    container_name: bitrender-backend-DEV
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - bitrender-backend-DEV-data:/data
      - bitrender-backend-DEV-fish:/home/vscode/.local/share/fish
    init: true
    command: sleep infinity
    user: vscode

  db:
    container_name: bitrender-database-DEV
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - bitrender-database-DEV:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bitrender-DEV
      POSTGRES_PASSWORD: postgres
    network_mode: service:app
    command: -p 5432

  db-test:
    container_name: bitrender-database-TEST
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bitrender-TEST
      POSTGRES_PASSWORD: postgres
    network_mode: service:app
    command: -p 5433

volumes:
  bitrender-backend-DEV-data:
  bitrender-database-DEV:
  bitrender-backend-DEV-fish:
