// Generated by kea-typegen on Mon, 08 Aug 2022 20:55:25 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface logicType extends Logic {
  actionCreators: {};
  actionKeys: {};
  actionTypes: {};
  actions: {};
  defaults: {};
  events: {};
  key: undefined;
  listeners: {};
  path: ['test'];
  pathString: 'test';
  props: Record<string, unknown>;
  reducer: (state: any, action: any, fullState: any) => {};
  reducers: {};
  selector: (state: any) => {};
  selectors: {};
  sharedListeners: {};
  values: {};
  _isKea: true;
  _isKeaWithKey: false;
}
