// Generated by kea-typegen on Sat, 21 May 2022 16:32:09 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

import { SidebarType, Theme } from './types'

export interface settingsLogicType extends Logic {
  actionCreators: {
    setSidebarType: (type: SidebarType) => {
      type: 'set sidebar type (settings)';
      payload: {
        type: SidebarType;
      };
    };
    setTheme: (theme: Theme) => {
      type: 'set theme (settings)';
      payload: {
        theme: Theme;
      };
    };
    setSlimSidebarState: (sidebarState: boolean) => {
      type: 'set slim sidebar state (settings)';
      payload: {
        sidebarState: boolean;
      };
    };
    toggleMobileSidebar: () => {
      type: 'toggle mobile sidebar (settings)';
      payload: {
        value: true;
      };
    };
  };
  actionKeys: {
    'set sidebar type (settings)': 'setSidebarType';
    'set theme (settings)': 'setTheme';
    'set slim sidebar state (settings)': 'setSlimSidebarState';
    'toggle mobile sidebar (settings)': 'toggleMobileSidebar';
  };
  actionTypes: {
    setSidebarType: 'set sidebar type (settings)';
    setTheme: 'set theme (settings)';
    setSlimSidebarState: 'set slim sidebar state (settings)';
    toggleMobileSidebar: 'toggle mobile sidebar (settings)';
  };
  actions: {
    setSidebarType: (type: SidebarType) => void;
    setTheme: (theme: Theme) => void;
    setSlimSidebarState: (sidebarState: boolean) => void;
    toggleMobileSidebar: () => void;
  };
  defaults: {
    theme: Theme;
    sidebarType: SidebarType;
    sidebarSlimActive: boolean;
    sidebarMobileActive: boolean;
  };
  events: {};
  key: undefined;
  listeners: {};
  path: ['settings'];
  pathString: 'settings';
  props: Record<string, unknown>;
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    theme: Theme;
    sidebarType: SidebarType;
    sidebarSlimActive: boolean;
    sidebarMobileActive: boolean;
  };
  reducers: {
    theme: (state: Theme, action: any, fullState: any) => Theme;
    sidebarType: (
      state: SidebarType,
      action: any,
      fullState: any,
    ) => SidebarType;
    sidebarSlimActive: (state: boolean, action: any, fullState: any) => boolean;
    sidebarMobileActive: (
      state: boolean,
      action: any,
      fullState: any,
    ) => boolean;
  };
  selector: (state: any) => {
    theme: Theme;
    sidebarType: SidebarType;
    sidebarSlimActive: boolean;
    sidebarMobileActive: boolean;
  };
  selectors: {
    theme: (state: any, props?: any) => Theme;
    sidebarType: (state: any, props?: any) => SidebarType;
    sidebarSlimActive: (state: any, props?: any) => boolean;
    sidebarMobileActive: (state: any, props?: any) => boolean;
  };
  sharedListeners: {};
  values: {
    theme: Theme;
    sidebarType: SidebarType;
    sidebarSlimActive: boolean;
    sidebarMobileActive: boolean;
  };
  _isKea: true;
  _isKeaWithKey: false;
}
