// Generated by kea-typegen on Tue, 02 Aug 2022 19:09:20 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { IRouteLogic } from '../../interfaces/route'
import type { IUserService } from '../../../services/interfaces/index'
import type { RequestStatus } from '../../../types/service'

export interface logicType extends Logic {
  actionCreators: {
    login: (
      username: string,
      password: string,
    ) => {
      type: 'login (logic.core.login.index)';
      payload: {
        username: string;
        password: string;
      };
    };
    loginSuccess: () => {
      type: 'login success (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
    loginFailure: (errorDetail?: unknown) => {
      type: 'login failure (logic.core.login.index)';
      payload: {
        errorDetail: unknown;
      };
    };
    logout: () => {
      type: 'logout (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
    logoutSuccess: () => {
      type: 'logout success (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
    logoutFailure: (errorDetail?: unknown) => {
      type: 'logout failure (logic.core.login.index)';
      payload: {
        errorDetail: unknown;
      };
    };
  };
  actionKeys: {
    'login (logic.core.login.index)': 'login';
    'login success (logic.core.login.index)': 'loginSuccess';
    'login failure (logic.core.login.index)': 'loginFailure';
    'logout (logic.core.login.index)': 'logout';
    'logout success (logic.core.login.index)': 'logoutSuccess';
    'logout failure (logic.core.login.index)': 'logoutFailure';
  };
  actionTypes: {
    login: 'login (logic.core.login.index)';
    loginSuccess: 'login success (logic.core.login.index)';
    loginFailure: 'login failure (logic.core.login.index)';
    logout: 'logout (logic.core.login.index)';
    logoutSuccess: 'logout success (logic.core.login.index)';
    logoutFailure: 'logout failure (logic.core.login.index)';
  };
  actions: {
    login: (username: string, password: string) => void;
    loginSuccess: () => void;
    loginFailure: (errorDetail?: unknown) => void;
    logout: () => void;
    logoutSuccess: () => void;
    logoutFailure: (errorDetail?: unknown) => void;
  };
  defaults: {
    loginStatus: RequestStatus;
    loginErrorDetail: null | unknown;
    logoutStatus: RequestStatus;
  };
  events: {};
  key: undefined;
  listeners: {
    login: ((
      action: {
        type: 'login (logic.core.login.index)';
        payload: {
          username: string;
          password: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    loginSuccess: ((
      action: {
        type: 'login success (logic.core.login.index)';
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
  };
  path: ['logic', 'core', 'login', 'index'];
  pathString: 'logic.core.login.index';
  props: {
    deps: {
      routeLogic: IRouteLogic;
      userService: IUserService;
    };
  };
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    loginStatus: RequestStatus;
    loginErrorDetail: null | unknown;
    logoutStatus: RequestStatus;
  };
  reducers: {
    loginStatus: (
      state: RequestStatus,
      action: any,
      fullState: any,
    ) => RequestStatus;
    loginErrorDetail: (
      state: null | unknown,
      action: any,
      fullState: any,
    ) => null | unknown;
    logoutStatus: (
      state: RequestStatus,
      action: any,
      fullState: any,
    ) => RequestStatus;
  };
  selector: (state: any) => {
    loginStatus: RequestStatus;
    loginErrorDetail: null | unknown;
    logoutStatus: RequestStatus;
  };
  selectors: {
    loginStatus: (state: any, props?: any) => RequestStatus;
    loginErrorDetail: (state: any, props?: any) => null | unknown;
    logoutStatus: (state: any, props?: any) => RequestStatus;
  };
  sharedListeners: {};
  values: {
    loginStatus: RequestStatus;
    loginErrorDetail: null | unknown;
    logoutStatus: RequestStatus;
  };
  _isKea: true;
  _isKeaWithKey: false;
}
