// Generated by kea-typegen on Sun, 07 Aug 2022 15:54:54 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { IRouteLogic } from '../../interfaces/route'
import type { IUserService } from '../../../services/interfaces/index'
import type { IUserValidators } from '../../../validators/interfaces/index'
import type { RequestStatus } from '../../../types/service'

export interface logicType extends Logic {
  actionCreators: {
    checkLoggedIn: () => {
      type: 'check logged in (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
    login: (
      username: string,
      password: string,
    ) => {
      type: 'login (logic.core.login.index)';
      payload: {
        username: string;
        password: string;
      };
    };
    loginSuccess: () => {
      type: 'login success (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
    loginFailure: (errorDetail?: unknown) => {
      type: 'login failure (logic.core.login.index)';
      payload: {
        errorDetail: unknown;
      };
    };
    logout: () => {
      type: 'logout (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
    logoutSuccess: () => {
      type: 'logout success (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
    logoutFailure: (errorDetail?: unknown) => {
      type: 'logout failure (logic.core.login.index)';
      payload: {
        errorDetail: unknown;
      };
    };
    register: (
      email: string,
      username: string,
      password: string,
    ) => {
      type: 'register (logic.core.login.index)';
      payload: {
        email: string;
        username: string;
        password: string;
      };
    };
    registerSuccess: () => {
      type: 'register success (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
    registerFailure: (errorDetail?: unknown) => {
      type: 'register failure (logic.core.login.index)';
      payload: {
        errorDetail: unknown;
      };
    };
    registerResetStatus: () => {
      type: 'register reset status (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
    setRegisterWeakPassword: (weakPassword: boolean) => {
      type: 'set register weak password (logic.core.login.index)';
      payload: {
        weakPassword: boolean;
      };
    };
    setRegisterWrongEmail: (wrongEmail: boolean) => {
      type: 'set register wrong email (logic.core.login.index)';
      payload: {
        wrongEmail: boolean;
      };
    };
  };
  actionKeys: {
    'check logged in (logic.core.login.index)': 'checkLoggedIn';
    'login (logic.core.login.index)': 'login';
    'login success (logic.core.login.index)': 'loginSuccess';
    'login failure (logic.core.login.index)': 'loginFailure';
    'logout (logic.core.login.index)': 'logout';
    'logout success (logic.core.login.index)': 'logoutSuccess';
    'logout failure (logic.core.login.index)': 'logoutFailure';
    'register (logic.core.login.index)': 'register';
    'register success (logic.core.login.index)': 'registerSuccess';
    'register failure (logic.core.login.index)': 'registerFailure';
    'register reset status (logic.core.login.index)': 'registerResetStatus';
    'set register weak password (logic.core.login.index)': 'setRegisterWeakPassword';
    'set register wrong email (logic.core.login.index)': 'setRegisterWrongEmail';
  };
  actionTypes: {
    checkLoggedIn: 'check logged in (logic.core.login.index)';
    login: 'login (logic.core.login.index)';
    loginSuccess: 'login success (logic.core.login.index)';
    loginFailure: 'login failure (logic.core.login.index)';
    logout: 'logout (logic.core.login.index)';
    logoutSuccess: 'logout success (logic.core.login.index)';
    logoutFailure: 'logout failure (logic.core.login.index)';
    register: 'register (logic.core.login.index)';
    registerSuccess: 'register success (logic.core.login.index)';
    registerFailure: 'register failure (logic.core.login.index)';
    registerResetStatus: 'register reset status (logic.core.login.index)';
    setRegisterWeakPassword: 'set register weak password (logic.core.login.index)';
    setRegisterWrongEmail: 'set register wrong email (logic.core.login.index)';
  };
  actions: {
    checkLoggedIn: () => void;
    login: (username: string, password: string) => void;
    loginSuccess: () => void;
    loginFailure: (errorDetail?: unknown) => void;
    logout: () => void;
    logoutSuccess: () => void;
    logoutFailure: (errorDetail?: unknown) => void;
    register: (email: string, username: string, password: string) => void;
    registerSuccess: () => void;
    registerFailure: (errorDetail?: unknown) => void;
    registerResetStatus: () => void;
    setRegisterWeakPassword: (weakPassword: boolean) => void;
    setRegisterWrongEmail: (wrongEmail: boolean) => void;
  };
  defaults: {
    loginStatus: RequestStatus;
    loginErrorDetail: null | unknown;
    logoutStatus: RequestStatus;
    registerStatus: RequestStatus;
    registerWeakPassword: boolean;
    registerWrongEmail: boolean;
    registerErrorDetail: null | unknown;
  };
  events: {};
  key: undefined;
  listeners: {
    checkLoggedIn: ((
      action: {
        type: 'check logged in (logic.core.login.index)';
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    login: ((
      action: {
        type: 'login (logic.core.login.index)';
        payload: {
          username: string;
          password: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    loginSuccess: ((
      action: {
        type: 'login success (logic.core.login.index)';
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
    register: ((
      action: {
        type: 'register (logic.core.login.index)';
        payload: {
          email: string;
          username: string;
          password: string;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
  };
  path: ['logic', 'core', 'login', 'index'];
  pathString: 'logic.core.login.index';
  props: {
    deps: {
      routeLogic: IRouteLogic;
      userService: IUserService;
      userValidators: IUserValidators;
    };
  };
  reducer: (
    state: any,
    action: any,
    fullState: any,
  ) => {
    loginStatus: RequestStatus;
    loginErrorDetail: null | unknown;
    logoutStatus: RequestStatus;
    registerStatus: RequestStatus;
    registerWeakPassword: boolean;
    registerWrongEmail: boolean;
    registerErrorDetail: null | unknown;
  };
  reducers: {
    loginStatus: (
      state: RequestStatus,
      action: any,
      fullState: any,
    ) => RequestStatus;
    loginErrorDetail: (
      state: null | unknown,
      action: any,
      fullState: any,
    ) => null | unknown;
    logoutStatus: (
      state: RequestStatus,
      action: any,
      fullState: any,
    ) => RequestStatus;
    registerStatus: (
      state: RequestStatus,
      action: any,
      fullState: any,
    ) => RequestStatus;
    registerWeakPassword: (
      state: boolean,
      action: any,
      fullState: any,
    ) => boolean;
    registerWrongEmail: (
      state: boolean,
      action: any,
      fullState: any,
    ) => boolean;
    registerErrorDetail: (
      state: null | unknown,
      action: any,
      fullState: any,
    ) => null | unknown;
  };
  selector: (state: any) => {
    loginStatus: RequestStatus;
    loginErrorDetail: null | unknown;
    logoutStatus: RequestStatus;
    registerStatus: RequestStatus;
    registerWeakPassword: boolean;
    registerWrongEmail: boolean;
    registerErrorDetail: null | unknown;
  };
  selectors: {
    loginStatus: (state: any, props?: any) => RequestStatus;
    loginErrorDetail: (state: any, props?: any) => null | unknown;
    logoutStatus: (state: any, props?: any) => RequestStatus;
    registerStatus: (state: any, props?: any) => RequestStatus;
    registerWeakPassword: (state: any, props?: any) => boolean;
    registerWrongEmail: (state: any, props?: any) => boolean;
    registerErrorDetail: (state: any, props?: any) => null | unknown;
  };
  sharedListeners: {};
  values: {
    loginStatus: RequestStatus;
    loginErrorDetail: null | unknown;
    logoutStatus: RequestStatus;
    registerStatus: RequestStatus;
    registerWeakPassword: boolean;
    registerWrongEmail: boolean;
    registerErrorDetail: null | unknown;
  };
  _isKea: true;
  _isKeaWithKey: false;
}
