// Generated by kea-typegen on Mon, 18 Jul 2022 17:34:18 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { IUserService } from '../../../services/interfaces/index'

export interface logicType extends Logic {
  actionCreators: {
    loadCurrentUser: () => {
      type: 'load current user (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
    openApp: () => {
      type: 'open app (logic.core.login.index)';
      payload: {
        value: true;
      };
    };
  };
  actionKeys: {
    'load current user (logic.core.login.index)': 'loadCurrentUser';
    'open app (logic.core.login.index)': 'openApp';
  };
  actionTypes: {
    loadCurrentUser: 'load current user (logic.core.login.index)';
    openApp: 'open app (logic.core.login.index)';
  };
  actions: {
    loadCurrentUser: () => void;
    openApp: () => void;
  };
  defaults: {};
  events: {};
  key: undefined;
  listeners: {
    loadCurrentUser: ((
      action: {
        type: 'load current user (logic.core.login.index)';
        payload: {
          value: true;
        };
      },
      previousState: any,
    ) => void | Promise<void>)[];
  };
  path: ['logic', 'core', 'login', 'index'];
  pathString: 'logic.core.login.index';
  props: {
    deps: {
      userService: IUserService;
    };
  };
  reducer: (state: any, action: any, fullState: any) => {};
  reducers: {};
  selector: (state: any) => {};
  selectors: {};
  sharedListeners: {};
  values: {};
  _isKea: true;
  _isKeaWithKey: false;
}
